# Generated by Django 2.1.5 on 2019-01-09 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Railwayticket', '0002_userdetails_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='status',
            field=models.TextField(null=True),
        ),
    ]
