# Generated by Django 2.1.5 on 2019-01-09 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Railwayticket', '0004_auto_20190109_1018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='id',
            new_name='user_id',
        ),
    ]
