# Generated by Django 2.1.5 on 2019-01-09 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Railwayticket', '0005_auto_20190109_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='coach',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
